### ISSUE TITLE
Final pdf file location?

### ISSUE THREAD

**Issue by bountrisv** [CPanourgias/Final-thesis#1]
Που είναι ρε η διπλωματική σου compiled, ανεβασε τη να σκρολαρουμε!

**Comment by CPanourgias** [comment]
Wait and see, ερχονται οι διορθωσεις

**Comment by bountrisv** [comment]
το pdf που ειναι σπαμ σπαμ σπαμ

**Comment by actondev** [comment]
@bvasilis κανε pull request :D

**Comment by bountrisv** [comment]
fantare? καλα λες, πουθενα ο @CPanourgias

**Comment by CPanourgias** [comment]
Είμαι άφαντος @bvasilis

**Comment by bountrisv** [comment]
merged :tada: :tada:
